### ISSUE TITLE
Only 1.82% of Android devices seem to be able to support this execution environment

### ISSUE THREAD

**Issue by litherum** [gpuweb/spirv-execution-env#37]
The latest version of [Vulkan spec](https://www.khronos.org/registry/vulkan/specs/1.1/html/chap35.html#_versions_and_formats) (version 1.1.127):

> A Vulkan 1.1 implementation must support the 1.0, 1.1, 1.2, and 1.3 versions of SPIR-V

This [environment document](https://github.com/gpuweb/spirv-execution-env/blob/master/execution-env.md):

> The memory model declared must be VulkanKHR.

The latest version of the [SPIR-V spec](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#Memory_Model):

> VulkanKHR : Missing before version 1.5.
>
> Also see extension: SPV_KHR_vulkan_memory_model

[GPUInfo](https://vulkan.gpuinfo.org/displayextension.php?name=VK_KHR_vulkan_memory_model):

> VK_KHR_vulkan_memory_model | Android: 1.82%

![Screen Shot 2019-11-08 at 11 56 37 AM](https://user-images.githubusercontent.com/918903/68506953-95483300-021f-11ea-90e1-a8e61b8b7655.png)

**Comment by litherum** [comment]
(As an aside, having to cross-reference 3 documents to gather information like this is quite unfortunate)

**Comment by dneto0** [comment]
Similarly, the Vulkan memory model is not supported natively by DX12 or Metal.

The limitations described by the execution environment are designed to allow us to convert a shader with VulkanKHR memory model to a shader with GLSL450 memory model.  The plan is that a WebGPU implementation that backs onto a Vulkan API would _likely_ have to do that conversion.  (That conversion can be pessimizing.)

For example, the limitations on atomics (https://github.com/gpuweb/spirv-execution-env/blob/master/execution-env.md#atomic-instructions ) imply that only "relaxed" atomics are permitted, but not acquire, release, or acquire-release.  Relaxed atomics are supported by a broad set of implementations across Vulkan, Metal, and DX12.

The idea behind specifying the VulkanKHR memory model was to get the benefit of a formally specified model.  I'm not aware of another model which applies to a wide range of GPUs and which is comparably-well specified.

In any case, we would need write WebGPU conformance tests to ensure correct operation across all implementations.

**Comment by dneto0** [comment]
Note:  GPUInfo is a great crowd-sourced resource.  However, its data are not weighted by market size (number of units).  If I understand correctly, the numbers reported above count the number of unique configurations reported.

Nevertheless your point is well taken, that the full VulkanKHR feature is not broadly supported by Vulkan implementations today.

**Comment by dneto0** [comment]
The spec is an "as-if" spec, so all that matters is behaviour rather than the declared functionality.  If it passes the tests, and the tests are complete enough then it conforms to the spec.

Even so, WGSL/WebGPU removes a lot of features.  E.g. no acquire-release semantics.  WGSL will only have relaxed atomics.
