### ISSUE TITLE
Simplify the phrasing of robust-access rules

### ISSUE THREAD

**Issue by dneto0** [gpuweb/spirv-execution-env#4]
See https://github.com/gpuweb/spirv-execution-env/pull/3#pullrequestreview-177438702

The phrasing for behaviour on out-of-bounds accesses for robust-access is confusing:

> Similarly to OpenGL's `GL_KHR_robust_buffer` extension, out of bounds accesses must produce one of the following behaviors:

> * Be discarded for writes
> * Access any location within the resource for reads and writes
> * Return zero values for reads or (0, 0, 0, X) with X being 0, 1, -1, or extrema for integers, or -0.0, +0.0, -1.0, +1.0 for floating point values
> * Atomics can return undefined values.

**Comment by dneto0** [comment]
The Vulkan spec has this phrased much more clearly:

https://github.com/KhronosGroup/Vulkan-Docs/blob/master/chapters/features.txt#L207

**Comment by dneto0** [comment]
What do you think @Kangz

**Comment by Kangz** [comment]
I agree that the phrasing in Vulkan is much more clear and detailed. The current PR is "good enough" for now but definitely not spec quality.
